def buildFile = new File(project.projectDir.absoluteFile.getParent(), "build_library_java.gradle")
apply from: rootProject.file(buildFile)

android {
    namespace "afkt_replace.replace"
}

dependencies {
    implementation deps.kotlin.stdlib
    // DevApp - Android 工具类库
    implementation deps.dev.dev_app
}