apply from: rootProject.file(files_component.build_library_gradle)

android {
    sourceSets {
        main {
            // 优化 res 资源管理, 使用 sourceSets 资源分包
            res.srcDirs = [
                    'src/main/res', // 模块通用资源文件
                    'src/main/res-base', // Base 基础资源
                    'src/main/res-tools', // tools 通用使用
                    'src/main/res-view-assist', // ViewAssist 骨架辅助类
            ]
        }
    }
}

dependencies {

    // 核心基础依赖库 ( 编译但不参与打包 )
    api project(':core_base_lib')

    // ===================
    // = core - 核心开发库 =
    // ===================

    // 通用配置、常量 lib
    api project(':core_lib_config')
    // 通用多语言 lib
    api project(':core_lib_language')
    // APP 主题、换肤相关控制
    api project(':core_lib_ui_skin')

    // ====================
    // = libs - 第三方库依赖 =
    // ====================

    // ==============
    // = 常用开发组件 =
    // ==============

    // 下拉刷新框架 https://github.com/scwang90/SmartRefreshLayout
    api deps_lib.common_widget.smartrefreshlayout
    api deps_lib.common_widget.smartrefresh_header_classics // 经典刷新头
    api deps_lib.common_widget.smartrefresh_footer_classics // 经典加载

    // ===================
    // = UI 效果相关组件库 =
    // ===================

    // LoadingDrawable https://github.com/dinuscxj/LoadingDrawable
    api deps_lib.ui_widget.loading_drawable
}