def buildFile = new File(project.projectDir.absoluteFile.getParent(), "build_library_java.gradle")
apply from: rootProject.file(buildFile)

android {
    namespace "afkt_replace.standard"
}

dependencies {
    implementation deps.kotlin.stdlib
    // DevApp - Android 工具类库
    implementation deps.dev.dev_app
    // Gson https://github.com/google/gson
    implementation deps_lib.common.gson
}